### ISSUE TITLE
Lógica do personagem

### ISSUE THREAD

**Issue by frankzeka** [frankzeka/WalkingPedroII#2]
Teclas de movimentação. Mouse mexe a cabeça.

**Comment by Allex2098** [comment]
Fiz a primeira parte da lógica da movimentação básica do personagem

**Comment by BlackburnRX** [comment]
qual parte da movimentação?

**Comment by BlackburnRX** [comment]
consegui colocar a movimentação da câmera, mas ainda precisa de alguns ajustes em relação ao campo de visão

**Comment by frankzeka** [comment]
Certo, essa tarefa está finalizada.
